apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: only-ingress-can-access-api
  namespace: sandbox
spec:
  podSelector:
    matchLabels:
      app: kraken-api
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgres

