apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: only-api-can-access-db
  namespace: sandbox
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: kraken-api
