version: "3"
services:
  api:
    build:
      context: api
      dockerfile: api/Dockerfile
    container_name: api
    ports:
      - "80:80"

  web:
    build:
      context: web
      dockerfile: web/Dockerfile
    container_name: web
    ports:
      - "80:80"
      - "443:443"

  db:
    container_name: db
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data