apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "kraken.fullname" . }}-my-ca-issuer
  labels:
  {{- include "kraken.labels" . | nindent 4 }}
spec:
  ca:
    secretName: root-secret