apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "kraken.fullname" . }}-selfsigned-cluster-issuer
  labels:
  {{- include "kraken.labels" . | nindent 4 }}
spec:
  selfSigned: {}