apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kraken.fullname" . }}-kraken-ingress
  labels:
    app: ingress
  {{- include "kraken.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/common-name: kraken.com
    cert-manager.io/issuer: my-ca-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: kraken.com
    http:
      paths:
      - backend:
          service:
            name: '{{ include "kraken.fullname" . }}-kraken-api-service'
            port:
              number: 443
        path: /api/(.*)
        pathType: Prefix
      - backend:
          service:
            name: '{{ include "kraken.fullname" . }}-kraken-web-service'
            port:
              number: 443
        path: /(.*)
        pathType: Prefix
  tls:
  - hosts:
    - kraken.com
    secretName: myingress-cert