apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kraken.fullname" . }}-kraken-config
  labels:
    app: kraken-api
  {{- include "kraken.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.krakenConfig.postgresDb | quote }}
  POSTGRES_HOSTNAME: {{ .Values.krakenConfig.postgresHostname | quote }}
  POSTGRES_PORT: {{ .Values.krakenConfig.postgresPort | quote }}
  POSTGRES_USERNAME: {{ .Values.krakenConfig.postgresUsername | quote }}