apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kraken.fullname" . }}-kraken-config-secret
  labels:
  {{- include "kraken.labels" . | nindent 4 }}
data:
  POSTGRES_PASSWORD: {{ required "krakenConfigSecret.postgresPassword is required"
    .Values.krakenConfigSecret.postgresPassword | b64enc | quote }}
type: Opaque