apiVersion: v1
kind: Service
metadata:
  name: {{ include "kraken.fullname" . }}-kraken-api-service
  labels:
  {{- include "kraken.labels" . | nindent 4 }}
spec:
  type: {{ .Values.krakenApiService.type }}
  selector:
    app: kraken-api
  {{- include "kraken.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.krakenApiService.ports | toYaml | nindent 2 -}}