apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kraken.fullname" . }}-monitor-role
  labels:
  {{- include "kraken.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list