apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kraken.fullname" . }}-nothing-to-ingress
  labels:
  {{- include "kraken.labels" . | nindent 4 }}
spec:
  ingress: []
  podSelector:
    matchLabels:
      app: ingress
  policyTypes:
  - Ingress