apiVersion: v1
kind: Service
metadata:
  name: {{ include "kraken.fullname" . }}-postgres-service
  labels:
    app: postgres
  {{- include "kraken.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresService.type }}
  selector:
    app: postgres
  {{- include "kraken.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.postgresService.ports | toYaml | nindent 2 -}}