apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kraken.fullname" . }}-postgres-deployment
  labels:
  {{- include "kraken.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgresDeployment.replicas }}
  selector:
    matchLabels:
      app: postgres
    {{- include "kraken.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: postgres
      {{- include "kraken.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: {{ include "kraken.fullname" . }}-kraken-config-secret
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "kraken.fullname" . }}-kraken-config
        image: {{ .Values.postgresDeployment.postgresContainer.image.repository }}:{{ .Values.postgresDeployment.postgresContainer.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.postgresDeployment.postgresContainer.imagePullPolicy
          }}
        name: postgres-container
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb
          subPath: pg
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: {{ include "kraken.fullname" . }}-postgres-pv-claim