apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "kraken.fullname" . }}-postgres-pv-volumn
  labels:
    app: postgres
    type: local
  {{- include "kraken.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /opt/postgre/data
  storageClassName: microk8s-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kraken.fullname" . }}-postgres-pv-claim
  labels:
    app: postgres
  {{- include "kraken.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.postgresPvClaim.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.postgresPvClaim.storageClass | quote }}