apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kraken.fullname" . }}-my-selfsigned-ca
  labels:
  {{- include "kraken.labels" . | nindent 4 }}
spec:
  commonName: my-selfsigned-ca
  dnsNames: []
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: '{{ include "kraken.fullname" . }}-selfsigned-cluster-issuer'
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: root-secret