apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kraken.fullname" . }}-sysadmin-binding
  labels:
  {{- include "kraken.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "kraken.fullname" . }}-sysadmin-role'
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: sysadmin
  namespace: '{{ .Release.Namespace }}'