apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kraken.fullname" . }}-web-cannot-access-anything
  labels:
  {{- include "kraken.labels" . | nindent 4 }}
spec:
  egress: []
  podSelector:
    matchLabels:
      app: kraken-web
  policyTypes:
  - Egress