apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: maintainer-binding
  namespace: sandbox
subjects:
- kind: User
  name: maintainer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: maintainer-role
  apiGroup: rbac.authorization.k8s.io