apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: maintainer-role
  namespace: sandbox
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]