apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-binding
  namespace: sandbox
subjects:
- kind: User
  name: monitor
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: monitor-role
  apiGroup: rbac.authorization.k8s.io