apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sysadmin-binding
  namespace: sandbox
subjects:
- kind: User
  name: sysadmin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: sysadmin-role
  apiGroup: rbac.authorization.k8s.io