apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sysadmin-role
  namespace: sandbox
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete", "create"]