apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kraken-ingress
  annotations:
    # cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    cert-manager.io/issuer: my-ca-issuer
    cert-manager.io/common-name: kraken.com
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  namespace: sandbox
spec:
  rules:
    - host: kraken.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kraken-web-service
                port:
                  number: 80
    - host: api.kraken.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kraken-api-service
                port:
                  number: 80
  tls:
    - hosts:
        - kraken.com
        - api.kraken.com
      secretName: root-secret
