apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-policies
  namespace: sandbox
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: kraken-api
