# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: postgres-pv-volume
#   namespace: sandbox
#   labels:
#     type: local
#     app: postgres
# spec:
#   # storageClassName: microk8s-hostpath
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/opt/postgre/data"
# ---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: sandbox
  labels:
    app: postgres
spec:
  # storageClassName: microk8s-hostpath
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
