apiVersion: v1
kind: ConfigMap
metadata:
  name: kraken-api-config
  labels: 
    app: kraken-api
  namespace: sandbox
data:
  PSQL_PORT: "5432"
  PSQL_USERNAME: postgresadmin
  PSQL_DATABASE: postgresdb
  PSQL_HOSTNAME: postgres-service