# Only use this in development.
# Leaving this out of k8s will disable access to the database from the outside,
# but will still enable the api to connect to the database

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30001
  selector:
    app: postgres
