apiVersion: apps/v1
kind: Deployment
metadata:
  name: kraken-web-deployment-canary
  namespace: sandbox
  labels:
    app: kraken-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kraken-web
      version: v2.0.0
  template:
    metadata:
      labels:
        app: kraken-web
        version: v2.0.0
    spec:
      containers:
        - name: kraken-web-container
          image: ghcr.io/derk-b/kraken-web:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
