krakenApiDeployment:
  krakenApiContainer:
    image:
      repository: ghcr.io/derk-b/kraken-api
      tag: latest
    imagePullPolicy: Always
  replicas: 3
krakenApiService:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8888
  type: ClusterIP
krakenConfig:
  postgresDb: postgresdb
  postgresHostname: postgres-service
  postgresPort: "5432"
  postgresUser: postgres
krakenConfigSecret:
  postgresPassword: "admin123"
krakenWebDeployment:
  krakenWebContainer:
    image:
      repository: ghcr.io/derk-b/kraken-web
      tag: latest
    imagePullPolicy: Always
  replicas: 1
krakenWebService:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
kubernetesClusterDomain: cluster.local
postgresDeployment:
  postgresContainer:
    image:
      repository: postgres
      tag: 13.1-alpine
    imagePullPolicy: IfNotPresent
  replicas: 1
postgresService:
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
pvc:
  postgresPvClaim:
    storageClass: standard-rwo
    storageRequest: 5Gi
